class_name BlockOrientations
extends RefCounted
## Pure logic: the 24 axis-aligned rotations of a cube (spec 2.5).
##
## No dependence on the scene tree, per CLAUDE.md ("core/" holds pure rule
## logic). A block's rotation is stored as an integer index into this table so
## it can never drift the way the original's free rotation did (spec 1.7):
## every step below maps one valid index to another valid index, and four yaw
## steps always return to the start.
##
## The table is built once, lazily, by breadth-first closure of the three
## 90-degree generators (yaw/pitch/roll) starting from the identity. Because
## the rotation group of the cube has exactly 24 elements and is generated by
## those three quarter turns, the closure is guaranteed to contain all 24 and
## nothing else, and every generator step from any element stays inside it.

const ORIENTATION_COUNT: int = 24

static var _orientations: Array[Basis] = []
static var _built: bool = false


static func count() -> int:
	_ensure_built()
	return _orientations.size()


static func get_basis(index: int) -> Basis:
	_ensure_built()
	return _orientations[index]


static func index_of(basis: Basis) -> int:
	_ensure_built()
	for i: int in range(_orientations.size()):
		if _basis_equal(_orientations[i], basis):
			return i
	return -1


static func step_yaw_ccw(index: int) -> int:
	return _step(index, Basis(Vector3.UP, PI / 2.0))


static func step_yaw_cw(index: int) -> int:
	return _step(index, Basis(Vector3.UP, -PI / 2.0))


static func step_pitch_fwd(index: int) -> int:
	return _step(index, Basis(Vector3.RIGHT, PI / 2.0))


static func step_pitch_back(index: int) -> int:
	return _step(index, Basis(Vector3.RIGHT, -PI / 2.0))


static func step_roll_left(index: int) -> int:
	return _step(index, Basis(Vector3.FORWARD, PI / 2.0))


static func step_roll_right(index: int) -> int:
	return _step(index, Basis(Vector3.FORWARD, -PI / 2.0))


static func _step(index: int, delta: Basis) -> int:
	_ensure_built()
	var current: Basis = _orientations[index]
	var next: Basis = (delta * current).orthonormalized()
	var result: int = index_of(next)
	if result == -1:
		push_error("BlockOrientations: step produced an orientation outside the 24-entry table.")
		return index
	return result


static func _ensure_built() -> void:
	if _built:
		return
	_orientations.clear()
	var generators: Array[Basis] = [
		Basis(Vector3.UP, PI / 2.0),
		Basis(Vector3.RIGHT, PI / 2.0),
		Basis(Vector3.FORWARD, PI / 2.0),
	]
	var frontier: Array[Basis] = [Basis.IDENTITY]
	_orientations.append(Basis.IDENTITY)
	while frontier.size() > 0:
		var current: Basis = frontier.pop_back()
		for generator: Basis in generators:
			var candidate: Basis = (generator * current).orthonormalized()
			if _add_unique(candidate):
				frontier.append(candidate)
	_built = true


static func _add_unique(basis: Basis) -> bool:
	for existing: Basis in _orientations:
		if _basis_equal(existing, basis):
			return false
	_orientations.append(basis)
	return true


static func _basis_equal(a: Basis, b: Basis) -> bool:
	return a[0].is_equal_approx(b[0]) and a[1].is_equal_approx(b[1]) and a[2].is_equal_approx(b[2])
